version: '3.8'

services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=bookmarks'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
